# Generated by Django 3.2.16 on 2025-11-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
